# Generated by Django 5.0.7 on 2024-07-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('services', models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('license_plate_no', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('services', models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('license_plate_no', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
