# Generated by Django 5.0.7 on 2024-07-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeservicerequest',
            name='year',
        ),
        migrations.RemoveField(
            model_name='carservicerequest',
            name='year',
        ),
    ]
