# Generated by Django 5.0.7 on 2024-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0002_remove_bikeservicerequest_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeservicerequest',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
