# Generated by Django 5.0.7 on 2024-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0003_bikeservicerequest_year_carservicerequest_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='services',
            field=models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre'), ('general_services', 'General Services'), ('starting_problem', 'Starting Problem'), ('fitment_service', 'Fitment Service'), ('key_unlock_assistance', 'Key-Unlock Assistance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carservicerequest',
            name='services',
            field=models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre'), ('general_services', 'General Services'), ('starting_problem', 'Starting Problem'), ('fitment_service', 'Fitment Service'), ('key_unlock_assistance', 'Key-Unlock Assistance')], max_length=50),
        ),
    ]
