# Generated by Django 5.0.7 on 2024-07-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('onroad', '0007_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bike_service_request',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car_service_request',
        ),
        migrations.AddField(
            model_name='booking',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
