# Generated by Django 5.0.7 on 2024-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0008_remove_booking_bike_service_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='object_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre'), ('general_services', 'General Services'), ('starting_problem', 'Starting Problem'), ('fitment_service', 'Fitment Service'), ('key_unlock_assistance', 'Key-Unlock Assistance')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
