# Generated by Django 5.0.7 on 2024-07-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0009_remove_booking_content_type_remove_booking_object_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
