# Generated by Django 5.0.7 on 2024-07-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0013_alter_booking_profile_alter_booking_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onroad.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre'), ('general_services', 'General Services'), ('starting_problem', 'Starting Problem'), ('fitment_service', 'Fitment Service'), ('key_unlock_assistance', 'Key-Unlock Assistance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
