# Generated by Django 5.0.7 on 2024-07-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0014_alter_booking_profile_alter_booking_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Success', max_length=20),
        ),
    ]
