# Generated by Django 5.0.7 on 2024-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0017_alter_checkout_payment_status_booking_bookingsuccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='booking_status',
            field=models.CharField(default='Success', max_length=20),
        ),
    ]
