# Generated by Django 5.0.7 on 2024-07-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0018_checkout_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsuccess',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingSuccess',
        ),
    ]
