# Generated by Django 5.0.7 on 2024-07-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0019_remove_bookingsuccess_booking_delete_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeservicerequest',
            old_name='username',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='carservicerequest',
            old_name='username',
            new_name='customer_name',
        ),
    ]
