# Generated by Django 5.0.7 on 2024-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0021_remove_bikeservicerequest_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeservicerequest',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='bikeservicerequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='bikeservicerequest',
            name='year',
        ),
        migrations.AddField(
            model_name='bikeservicerequest',
            name='customer_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikeservicerequest',
            name='phone_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='license_plate_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='services',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='vehicle_model',
            field=models.CharField(max_length=100),
        ),
    ]
