# Generated by Django 5.0.7 on 2024-09-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0022_remove_bikeservicerequest_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeservicerequest',
            name='booking_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bikeservicerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikeservicerequest',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='license_plate_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='onroad.profile'),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='services',
            field=models.CharField(choices=[('towing', 'Towing'), ('tire_replacement', 'Tire Replacement'), ('fuel_delivery', 'Fuel Delivery'), ('battery_jumpstart', 'Battery Jumpstart'), ('flat_tyre', 'Flat Tyre'), ('general_services', 'General Services'), ('starting_problem', 'Starting Problem'), ('fitment_service', 'Fitment Service'), ('key_unlock_assistance', 'Key-Unlock Assistance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bikeservicerequest',
            name='vehicle_model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carservicerequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests', to='onroad.profile'),
        ),
    ]
