# Generated by Django 5.0.7 on 2024-09-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0024_remove_bikeservicerequest_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='bike_service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='onroad.bikeservicerequest'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='car_service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='onroad.carservicerequest'),
        ),
    ]
