# Generated by Django 5.0.7 on 2024-09-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0025_alter_checkout_bike_service_request_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeservicerequest',
            options={'verbose_name': 'Bike Service Request', 'verbose_name_plural': 'Bike Service Requests'},
        ),
        migrations.AlterModelOptions(
            name='carservicerequest',
            options={'verbose_name': 'Car Service Request', 'verbose_name_plural': 'Car Service Requests'},
        ),
        migrations.AlterUniqueTogether(
            name='bikeservicerequest',
            unique_together={('profile', 'services', 'vehicle_model')},
        ),
        migrations.AlterUniqueTogether(
            name='carservicerequest',
            unique_together={('profile', 'services', 'vehicle_model')},
        ),
    ]
