# Generated by Django 5.0.7 on 2024-09-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0028_alter_carservicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeservicerequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onroad.profile'),
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onroad.profile'),
        ),
    ]
